apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashctrl-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cashctrl-db
  template:
    metadata:
      labels:
        app: cashctrl-db
    spec:
      containers:
      - name: db
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: cashctrl-secrets
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: cashctrl-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: cashctrl-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cashctrl-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
