# Generated by Django 6.0.3 on 2026-03-16 18:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("target_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=18)),
                ("provider", models.CharField(default="manual", max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("base_currency", "target_currency")},
            },
        ),
    ]
